[package]
name = "monk3i-download-manager"
version = "0.2.0"
description = "A reliable desktop download manager."
authors = ["Monk3i Systems"]
edition = "2021"

[lib]
name = "monk3i_download_manager_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "stream"] }
futures-util = "0.3"
dirs = "6"
tokio = { version = "1", features = ["fs", "io-util", "process", "macros"] }
percent-encoding = "2"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
