import { useEffect,useMemo,useRef,useState } from "react";
import { invoke } from "@tauri-apps/api/core";
import { listen } from "@tauri-apps/api/event";
import "./App.css";

type Status="downloading"|"paused"|"completed"|"cancelled"|"error";
type DownloadProgress={id:string;url:string;filename:string;downloaded:number;total:number|null;percent:number|null;speed:number;status:Status;path:string|null;error:string|null};
type ResourceInfo={url:string;kind:string;content_type:string|null;filename:string|null;size:number|null;final_url:string;status_code:number};
type QueueItem={id:string;url:string;filename:string;category:string};
type Options={headers:string[];proxy:string;speed_limit:number};
const HISTORY_KEY="monk3i-history-v1",OPTIONS_KEY="monk3i-network-v1",CATEGORY_KEY="monk3i-categories-v1",QUEUE_KEY="monk3i-queue-v1",MAX_ACTIVE=3;
const TEMP_MEDIA_NAMES=new Set(["Preparing media...","Downloading media...","Media download"]);
function formatBytes(n:number){if(n<1024)return `${n} B`;if(n<1024**2)return `${(n/1024).toFixed(1)} KB`;if(n<1024**3)return `${(n/1024**2).toFixed(1)} MB`;return `${(n/1024**3).toFixed(2)} GB`}
function formatSpeed(n:number){return `${formatBytes(n)}/s`}
function load<T>(k:string,f:T):T{try{const x=localStorage.getItem(k);return x?JSON.parse(x):f}catch{return f}}
function isMedia(u:string){try{const h=new URL(u).hostname.toLowerCase().replace(/^www\./,"");return ["youtube.com","youtu.be","youtube-nocookie.com","vimeo.com","dailymotion.com","tiktok.com","instagram.com","facebook.com","soundcloud.com"].some(d=>h===d||h.endsWith(`.${d}`))}catch{return false}}
function notify(title:string,body:string){try{if("Notification" in window&&Notification.permission==="granted")new Notification(title,{body})}catch{}}
function App(){
 const [url,setUrl]=useState("");const [downloads,setDownloads]=useState<DownloadProgress[]>([]);const [queue,setQueue]=useState<QueueItem[]>(()=>load(QUEUE_KEY,[]));const [history,setHistory]=useState<DownloadProgress[]>(()=>load(HISTORY_KEY,[]));const [categories,setCategories]=useState<Record<string,string>>(()=>load(CATEGORY_KEY,{}));const [speedLimits,setSpeedLimits]=useState<Record<string,number>>({});
 const [view,setView]=useState<"downloads"|"queue"|"completed"|"settings">("downloads");const [resource,setResource]=useState<ResourceInfo|null>(null);const [error,setError]=useState("");const [inspecting,setInspecting]=useState(false);const [details,setDetails]=useState<DownloadProgress|null>(null);const [search,setSearch]=useState("");const [category,setCategory]=useState("All");const [selected,setSelected]=useState<string[]>([]);const [options,setOptions]=useState<Options>(()=>load(OPTIONS_KEY,{headers:[],proxy:"",speed_limit:0}));const launchingCount=useRef(0);
 useEffect(()=>localStorage.setItem(HISTORY_KEY,JSON.stringify(history)),[history]);useEffect(()=>localStorage.setItem(QUEUE_KEY,JSON.stringify(queue)),[queue]);useEffect(()=>localStorage.setItem(CATEGORY_KEY,JSON.stringify(categories)),[categories]);useEffect(()=>localStorage.setItem(OPTIONS_KEY,JSON.stringify(options)),[options]);
 useEffect(()=>{if("Notification" in window&&Notification.permission==="default")Notification.requestPermission().catch(()=>{});let off:(()=>void)|undefined;listen<DownloadProgress>("download-progress",e=>{const x=e.payload;const next={...x,filename:TEMP_MEDIA_NAMES.has(x.filename)&&x.filename?x.filename:x.filename};setDownloads(cur=>{const i=cur.findIndex(d=>d.id===x.id);if(i<0)return[next,...cur];const p=cur[i],n={...next};if(x.status==="downloading"&&p.status==="downloading")n.downloaded=Math.max(p.downloaded,x.downloaded);const out=[...cur];out[i]=n;return out});if(["completed","cancelled","error"].includes(x.status)){setHistory(h=>[x,...h.filter(d=>d.id!==x.id)].slice(0,500));if(x.status==="completed")notify("Monk3i download complete",x.filename);if(x.status==="error")notify("Monk3i download failed",x.filename)}}).then(f=>off=f);return()=>off?.()},[]);
 useEffect(()=>{const unfinished=history.filter(d=>d.status==="downloading"||d.status==="paused");if(unfinished.length)setQueue(q=>[...unfinished.filter(d=>!q.some(x=>x.url===d.url)).map(d=>({id:`recovery-${Date.now()}-${d.id}`,url:d.url,filename:d.filename,category:categories[d.id]||"Other"})),...q])},[]);
 const active=useMemo(()=>downloads.filter(d=>d.status==="downloading"||d.status==="paused"||d.status==="error"),[downloads]);const running=downloads.filter(d=>d.status==="downloading").length;const occupied=downloads.filter(d=>d.status==="downloading"||d.status==="paused").length+launchingCount.current;
 useEffect(()=>{const slots=Math.max(0,MAX_ACTIVE-occupied);if(!slots||!queue.length)return;const items=queue.slice(0,slots);setQueue(q=>q.filter(x=>!items.some(i=>i.id===x.id)));launchingCount.current+=items.length;items.forEach(async item=>{try{const id=await invoke<string>("start_download",{url:item.url,options});setCategories(c=>({...c,[id]:item.category}))}catch(e){setError(String(e));setQueue(q=>q.some(x=>x.id===item.id)?q:[item,...q])}finally{launchingCount.current=Math.max(0,launchingCount.current-1)}})},[queue.length,occupied]);
 const inspect=async()=>{const u=url.trim();if(!u)return;setError("");setInspecting(true);try{setResource(await invoke<ResourceInfo>("inspect_url",{url:u}))}catch(e){setError(String(e))}finally{setInspecting(false)}};
 const add=()=>{const u=url.trim();if(!u)return;const filename=resource?.filename||(isMedia(u)?"Preparing media...":u.split("/").pop()||"Queued download");setQueue(q=>[...q,{id:`queue-${Date.now()}-${Math.random()}`,url:u,filename,category:category==="All"?"Other":category}]);setUrl("");setResource(null)};
 const control=async(id:string,a:"pause_download"|"resume_download"|"cancel_download")=>{try{await invoke(a,{id})}catch(e){setError(String(e))}};
 const retry=(d:DownloadProgress)=>{setQueue(q=>[...q,{id:`retry-${Date.now()}`,url:d.url,filename:d.filename,category:categories[d.id]||"Other"}]);setDownloads(x=>x.filter(y=>y.id!==d.id));setHistory(h=>h.filter(y=>y.id!==d.id))};
 const batch=(a:"pause"|"resume"|"cancel")=>{selected.forEach(id=>{const d=downloads.find(x=>x.id===id);if(d)control(id,a==="pause"?"pause_download":a==="resume"?"resume_download":"cancel_download")});setSelected([])};
 const setLimit=async(d:DownloadProgress,n:number)=>{try{await invoke("set_speed_limit",{id:d.id,bytesPerSecond:n});setSpeedLimits(x=>({...x,[d.id]:n}))}catch(e){setError(String(e))}};
 const matches=(d:DownloadProgress)=>{const q=search.toLowerCase();return(!q||d.filename.toLowerCase().includes(q)||d.url.toLowerCase().includes(q))&&(category==="All"||category===(categories[d.id]||"Other"))};
 const card=(d:DownloadProgress)=><article className="download-item" key={d.id}><div className="download-item-top"><div className="download-file-info"><input type="checkbox" checked={selected.includes(d.id)} onChange={e=>setSelected(s=>e.target.checked?[...s,d.id]:s.filter(x=>x!==d.id))}/><div className="download-file-icon">{d.status==="error"?"!":d.status==="paused"?"Ⅱ":"↓"}</div><div><h3>{d.filename}</h3><p>{formatBytes(d.downloaded)}{d.total!==null&&` / ${formatBytes(d.total)}`} · {categories[d.id]||"Other"}</p></div></div><div className="download-status">{d.status==="error"?"Error":d.status==="paused"?"Paused":`${Math.min(100,Math.max(0,d.percent??0)).toFixed(0)}%`}</div></div><div className="progress-track"><div className="progress-fill" style={{width:`${Math.min(100,Math.max(0,d.percent??0))}%`}}/></div><div className="download-item-bottom"><span>{d.error||formatSpeed(d.speed)}</span><div className="download-actions"><button className="download-control" onClick={()=>setDetails(d)}>Details</button>{d.status==="error"?<button className="download-control" onClick={()=>retry(d)}>Retry</button>:d.status!=="cancelled"&&<><button className="download-control" onClick={()=>control(d.id,d.status==="paused"?"resume_download":"pause_download")}>{d.status==="paused"?"Resume":"Pause"}</button><button className="download-control cancel-control" onClick={()=>control(d.id,"cancel_download")}>Cancel</button></>}</div></div></article>;
 const cats=["All","Software","Videos","Music","Images","Documents","Archives","Other"];const visible=active.filter(matches),completed=history.filter(d=>d.status==="completed"&&matches(d));
 return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">M</div><div><div className="brand-name">Monk3i</div><div className="brand-subtitle">Download Manager</div></div></div><nav className="sidebar-nav"><button className={`nav-item ${view==="downloads"?"active":""}`} onClick={()=>setView("downloads")}>↓ Downloads<span className="nav-count">{active.length}</span></button><button className={`nav-item ${view==="queue"?"active":""}`} onClick={()=>setView("queue")}>◷ Queue<span className="nav-count">{queue.length}</span></button><button className={`nav-item ${view==="completed"?"active":""}`} onClick={()=>setView("completed")}>✓ Completed<span className="nav-count">{history.filter(d=>d.status==="completed").length}</span></button><button className={`nav-item ${view==="settings"?"active":""}`} onClick={()=>setView("settings")}>⚙ Settings</button></nav><div className="sidebar-footer"><span>Monk3i Systems</span><span>v0.2.0</span></div></aside><main className="main-content"><header className="topbar"><div><p className="eyebrow">MONK3I SYSTEMS</p><h1>{view==="downloads"?"Downloads":view==="queue"?"Download Queue":view==="completed"?"Download History":"Settings"}</h1><p className="page-description">{view==="downloads"?"Manage, search and control your downloads.":view==="queue"?"Downloads waiting for an available slot.":view==="completed"?"Your completed downloads.":"Network, retry and notification controls."}</p></div></header>
 {view!=="settings"&&<div className="url-row" style={{marginBottom:16}}><input className="url-input" value={search} onChange={e=>setSearch(e.currentTarget.value)} placeholder="Search downloads..."/><select className="speed-select" value={category} onChange={e=>setCategory(e.currentTarget.value)}>{cats.map(x=><option key={x}>{x}</option>)}</select>{selected.length>0&&<><button className="download-control" onClick={()=>batch("pause")}>Pause selected</button><button className="download-control" onClick={()=>batch("resume")}>Resume selected</button><button className="download-control cancel-control" onClick={()=>batch("cancel")}>Cancel selected</button></>}</div>}
 {view==="settings"?<section className="downloads-panel settings-panel"><div className="section-heading"><div><h2>Phase 1 settings</h2><p>Retry, notifications, headers and proxy.</p></div></div><div className="setting-row"><div><strong>Default speed limit</strong><span>Applied to new downloads.</span></div><select className="speed-select" value={options.speed_limit} onChange={e=>setOptions(o=>({...o,speed_limit:Number(e.currentTarget.value)}))}><option value={0}>Unlimited</option><option value={131072}>128 KB/s</option><option value={262144}>256 KB/s</option><option value={524288}>512 KB/s</option><option value={1048576}>1 MB/s</option><option value={2097152}>2 MB/s</option><option value={5242880}>5 MB/s</option></select></div><div className="setting-row"><div><strong>Proxy</strong><span>HTTP/HTTPS proxy for new downloads.</span></div><input className="url-input" value={options.proxy} onChange={e=>setOptions(o=>({...o,proxy:e.currentTarget.value}))} placeholder="http://127.0.0.1:8080"/></div><div className="setting-row"><div><strong>Custom headers</strong><span>One header per line: Name: value</span></div><textarea className="url-input" rows={4} value={options.headers.join("\n")} onChange={e=>setOptions(o=>({...o,headers:e.currentTarget.value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean)}))}/></div><div className="setting-row"><div><strong>Notifications</strong><span>Completion and failure notifications.</span></div><button className="secondary-button" onClick={()=>notify("Monk3i","Notifications are working.")}>Test notification</button></div></section>
 :view==="queue"?<section className="downloads-panel"><div className="section-heading"><div><h2>Queue</h2><p>{queue.length} waiting.</p></div></div>{queue.length===0?<div className="empty-state"><h3>Queue is empty</h3></div>:<div className="download-list">{queue.map((q,i)=><article className="download-item" key={q.id}><div className="download-item-top"><div className="download-file-info"><div className="download-file-icon">◷</div><div><h3>{q.filename}</h3><p>{q.category} · {q.url}</p></div></div><div className="download-status">#{i+1}</div></div><div className="download-item-bottom"><span>Waiting for slot</span><button className="download-control cancel-control" onClick={()=>setQueue(x=>x.filter(y=>y.id!==q.id))}>Remove</button></div></article>)}</div>}</section>
 :view==="completed"?<section className="downloads-panel"><div className="section-heading"><div><h2>History</h2><p>Stored locally on this computer.</p></div><button className="download-control" onClick={()=>setHistory([])}>Clear history</button></div>{completed.length?<div className="download-list">{completed.map(card)}</div>:<div className="empty-state"><h3>No matching completed downloads</h3></div>}</section>
 :<><section className="add-card"><div className="add-card-copy"><div className="add-icon">↓</div><div><h2>Add a download</h2><p>Paste a URL and Monk3i will identify what it points to.</p></div></div><div className="url-row"><input className="url-input" value={url} onChange={e=>{setUrl(e.currentTarget.value);setResource(null);setError("")}} onKeyDown={e=>{if(e.key==="Enter")inspect()}} placeholder="https://example.com/file.zip"/><button className="secondary-button" onClick={inspect} disabled={inspecting}>{inspecting?"Checking...":"Detect"}</button><button className="primary-button" onClick={add}>+ Add Download</button></div>{resource&&<div className="resource-result"><div><strong>{resource.kind}</strong><span>{resource.filename||"No filename detected"}</span></div><span>{resource.content_type||""}</span><span>{resource.size!==null?formatBytes(resource.size):"Size unknown"}</span></div>}{error&&<p className="error-message">{error}</p>}</section><section className="downloads-panel"><div className="section-heading"><div><h2>Active Downloads</h2><p>{running} running · {queue.length} queued</p></div></div>{visible.length?<div className="download-list">{visible.map(card)}</div>:<div className="empty-state"><h3>No matching downloads</h3><p>Use search or categories to filter.</p></div>}</section></>}
 </main>{details&&<div className="details-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setDetails(null)}}><section className="details-modal"><div className="details-header"><div><p className="eyebrow">DOWNLOAD DETAILS</p><h2>{details.filename}</h2></div><button className="icon-button" onClick={()=>setDetails(null)}>×</button></div><div className="details-grid"><div><span>Status</span><strong>{details.status}</strong></div><div><span>Downloaded</span><strong>{formatBytes(details.downloaded)}</strong></div><div><span>Total</span><strong>{details.total===null?"Unknown":formatBytes(details.total)}</strong></div><div><span>Speed</span><strong>{formatSpeed(details.speed)}</strong></div><div className="details-wide"><span>URL</span><strong>{details.url}</strong></div><div className="details-wide"><span>Saved path</span><strong>{details.path||"Not available"}</strong></div></div><div className="speed-control"><div><strong>Speed limit</strong><span>{(speedLimits[details.id]??options.speed_limit)===0?"Unlimited":formatSpeed(speedLimits[details.id]??options.speed_limit)}</span></div><select className="speed-select" value={speedLimits[details.id]??options.speed_limit} onChange={e=>setLimit(details,Number(e.currentTarget.value))}><option value={0}>Unlimited</option><option value={131072}>128 KB/s</option><option value={262144}>256 KB/s</option><option value={524288}>512 KB/s</option><option value={1048576}>1 MB/s</option><option value={2097152}>2 MB/s</option><option value={5242880}>5 MB/s</option></select></div></section></div>}</div>}
export default App;
