import { useEffect, useMemo, useRef, useState } from "react";
import { invoke } from "@tauri-apps/api/core";
import { listen } from "@tauri-apps/api/event";
import "./App.css";

type Status = "downloading" | "paused" | "completed" | "cancelled" | "error";
type DownloadProgress = { id:string; url:string; filename:string; downloaded:number; total:number|null; percent:number|null; speed:number; status:Status; path:string|null; error:string|null };
type ResourceInfo = { url:string; kind:"file"|"image"|"video"|"audio"|"webpage"|"media_page"; content_type:string|null; filename:string|null; size:number|null; final_url:string; status_code:number };
type QueueItem = { id:string; url:string; filename:string };

const HISTORY_KEY="monk3i-history-v1";
const DEFAULT_SPEED_KEY="monk3i-default-speed-v1";
const MAX_ACTIVE=3;
const TEMP_MEDIA_NAMES=new Set(["Preparing media...","Downloading media...","Media download"]);

function formatBytes(bytes:number){if(bytes<1024)return `${bytes} B`;if(bytes<1024**2)return `${(bytes/1024).toFixed(1)} KB`;if(bytes<1024**3)return `${(bytes/1024**2).toFixed(1)} MB`;return `${(bytes/1024**3).toFixed(2)} GB`}
function formatSpeed(bytes:number){return `${formatBytes(bytes)}/s`}
function label(kind:ResourceInfo["kind"]){return kind==="media_page"?"Media page":kind==="webpage"?"Webpage":kind==="image"?"Image":kind==="video"?"Video":kind==="audio"?"Audio":"Direct file"}
function loadJson<T>(key:string,fallback:T):T{try{const v=localStorage.getItem(key);return v?JSON.parse(v):fallback}catch{return fallback}}

function App(){
 const [url,setUrl]=useState("");
 const [downloads,setDownloads]=useState<DownloadProgress[]>([]);
 const [queue,setQueue]=useState<QueueItem[]>([]);
 const [launchingCount,setLaunchingCount]=useState(0);
 const launchingUrls=useRef<string[]>([]);
 const filenameHints=useRef<Record<string,string>>({});
 const [history,setHistory]=useState<DownloadProgress[]>(()=>loadJson(HISTORY_KEY,[]));
 const [speedLimits,setSpeedLimits]=useState<Record<string,number>>({});
 const [defaultSpeed,setDefaultSpeed]=useState(()=>Number(localStorage.getItem(DEFAULT_SPEED_KEY)||0));
 const [view,setView]=useState<"downloads"|"queue"|"completed"|"settings">("downloads");
 const [resource,setResource]=useState<ResourceInfo|null>(null);
 const [error,setError]=useState("");
 const [inspecting,setInspecting]=useState(false);
 const [details,setDetails]=useState<DownloadProgress|null>(null);

 useEffect(()=>{let off:(()=>void)|undefined;listen<DownloadProgress>("download-progress",e=>{const x=e.payload;const launchIndex=launchingUrls.current.indexOf(x.url);if(launchIndex>=0){launchingUrls.current.splice(launchIndex,1);setLaunchingCount(n=>Math.max(0,n-1))}const hinted=filenameHints.current[x.url];const nextPayload={...x,filename:TEMP_MEDIA_NAMES.has(x.filename)&&hinted?hinted:x.filename};setDownloads(cur=>{const i=cur.findIndex(d=>d.id===x.id);if(i<0)return[nextPayload,...cur];const prev=cur[i],next={...nextPayload};if(x.status==="downloading"&&prev.status==="downloading"){next.downloaded=Math.max(prev.downloaded,x.downloaded);if(prev.total!==null&&(x.total===null||x.total<prev.total))next.total=prev.total;if(prev.percent!==null&&(x.percent===null||x.percent<prev.percent))next.percent=x.percent}const out=[...cur];out[i]=next;return out})}).then(f=>off=f);return()=>off?.()},[]);
 useEffect(()=>{localStorage.setItem(HISTORY_KEY,JSON.stringify(history))},[history]);
 useEffect(()=>{const terminal=downloads.filter(d=>["completed","cancelled","error"].includes(d.status));if(!terminal.length)return;setHistory(h=>{const ids=new Set(h.map(x=>x.id));return [...terminal.filter(x=>!ids.has(x.id)),...h].slice(0,100)})},[downloads]);

 const active=useMemo(()=>downloads.filter(d=>d.status==="downloading"||d.status==="paused"||d.status==="error"),[downloads]);
 const running=downloads.filter(d=>d.status==="downloading").length;
 const occupied=downloads.filter(d=>d.status==="downloading"||d.status==="paused").length+launchingCount;

 useEffect(()=>{const slots=Math.max(0,MAX_ACTIVE-occupied);if(slots===0||queue.length===0)return;const items=queue.slice(0,slots);setQueue(q=>q.filter(x=>!items.some(i=>i.id===x.id)));launchingUrls.current.push(...items.map(i=>i.url));setLaunchingCount(n=>n+items.length);items.forEach(item=>{invoke("start_download",{url:item.url}).catch(e=>{const i=launchingUrls.current.indexOf(item.url);if(i>=0)launchingUrls.current.splice(i,1);setLaunchingCount(n=>Math.max(0,n-1));setError(String(e));setQueue(q=>q.some(x=>x.id===item.id)?q:[item,...q])})})},[queue.length,occupied]);

 const inspect=async()=>{const u=url.trim();if(!u)return;setError("");setInspecting(true);try{setResource(await invoke<ResourceInfo>("inspect_url",{url:u}))}catch(e){setError(String(e))}finally{setInspecting(false)}};
 const add=()=>{const u=url.trim();if(!u)return;setError("");const filename=resource?.filename||u.split("/").pop()||"Queued download";filenameHints.current[u]=filename;setQueue(q=>[...q,{id:`queue-${Date.now()}-${Math.random()}`,url:u,filename}]);setUrl("");setResource(null)};
 const control=async(id:string,action:"pause_download"|"resume_download"|"cancel_download")=>{
  const previous=downloads.find(d=>d.id===id);if(!previous)return;
  const optimistic:Status=action==="pause_download"?"paused":action==="resume_download"?"downloading":"cancelled";
  setError("");
  setDownloads(cur=>cur.map(d=>d.id===id?{...d,status:optimistic,speed:optimistic==="downloading"?d.speed:0,error:null}:d));
  try{await invoke(action,{id})}catch(e){setDownloads(cur=>cur.map(d=>d.id===id?previous:d));setError(String(e))}
 };
 const setLimit=async(d:DownloadProgress,n:number)=>{try{await invoke("set_speed_limit",{id:d.id,bytesPerSecond:n});setSpeedLimits(x=>({...x,[d.id]:n}))}catch(e){setError(String(e))}};

 const card=(d:DownloadProgress)=><article className="download-item" key={d.id}><div className="download-item-top"><div className="download-file-info"><div className="download-file-icon">{d.status==="error"?"!":d.status==="paused"?"Ⅱ":"↓"}</div><div><h3>{d.filename}</h3><p>{formatBytes(d.downloaded)}{d.total!==null&&` / ${formatBytes(d.total)}`}</p></div></div><div className="download-status">{d.status==="error"?"Error":d.status==="paused"?"Paused":d.status==="cancelled"?"Cancelled":`${Math.min(100,Math.max(0,d.percent??0)).toFixed(0)}%`}</div></div><div className="progress-track"><div className="progress-fill" style={{width:`${Math.min(100,Math.max(0,d.percent??0))}%`}}/></div><div className="download-item-bottom"><span>{d.error||formatSpeed(d.speed)}</span><div className="download-actions"><button className="download-control" onClick={()=>setDetails(d)}>Details</button>{d.status!=="error"&&d.status!=="cancelled"&&<button className="download-control" onClick={()=>control(d.id,d.status==="paused"?"resume_download":"pause_download")}>{d.status==="paused"?"Resume":"Pause"}</button>}{d.status!=="error"&&d.status!=="cancelled"&&<button className="download-control cancel-control" onClick={()=>control(d.id,"cancel_download")}>Cancel</button>}</div></div></article>;

 return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">M</div><div><div className="brand-name">Monk3i</div><div className="brand-subtitle">Download Manager</div></div></div><nav className="sidebar-nav"><button className={`nav-item ${view==="downloads"?"active":""}`} onClick={()=>setView("downloads")}><span className="nav-icon">↓</span>Downloads<span className="nav-count">{active.length}</span></button><button className={`nav-item ${view==="queue"?"active":""}`} onClick={()=>setView("queue")}><span className="nav-icon">◷</span>Queue<span className="nav-count">{queue.length}</span></button><button className={`nav-item ${view==="completed"?"active":""}`} onClick={()=>setView("completed")}><span className="nav-icon">✓</span>Completed<span className="nav-count">{history.length}</span></button><button className={`nav-item ${view==="settings"?"active":""}`} onClick={()=>setView("settings")}><span className="nav-icon">⚙</span>Settings</button></nav><div className="sidebar-footer"><span>Monk3i Systems</span><span>v0.1.0</span></div></aside>
 <main className="main-content"><header className="topbar"><div><p className="eyebrow">MONK3I SYSTEMS</p><h1>{view==="downloads"?"Downloads":view==="queue"?"Download Queue":view==="completed"?"Download History":"Settings"}</h1><p className="page-description">{view==="downloads"?"Manage and monitor your downloads in one place.":view==="queue"?"Downloads waiting for an available slot.":view==="completed"?"Your recent download history.":"Control Monk3i download defaults."}</p></div></header>
 {view==="settings"?<section className="downloads-panel settings-panel"><div className="section-heading"><div><h2>Download settings</h2><p>Three simultaneous downloads are allowed.</p></div></div><div className="setting-row"><div><strong>Default speed limit</strong><span>Used when a download has no individual limit.</span></div><select className="speed-select" value={defaultSpeed} onChange={e=>{const n=Number(e.currentTarget.value);setDefaultSpeed(n);localStorage.setItem(DEFAULT_SPEED_KEY,String(n))}}><option value={0}>Unlimited</option><option value={131072}>128 KB/s</option><option value={262144}>256 KB/s</option><option value={524288}>512 KB/s</option><option value={1048576}>1 MB/s</option><option value={2097152}>2 MB/s</option><option value={5242880}>5 MB/s</option></select></div></section>
 :view==="queue"?<section className="downloads-panel"><div className="section-heading"><div><h2>Queue</h2><p>{queue.length} waiting.</p></div><span className="count-badge">{queue.length}</span></div>{queue.length===0?<div className="empty-state"><div className="empty-icon">◷</div><h3>Queue is empty</h3><p>Additional downloads will start automatically when a slot opens.</p></div>:<div className="download-list">{queue.map((q,i)=><article className="download-item" key={q.id}><div className="download-item-top"><div className="download-file-info"><div className="download-file-icon">◷</div><div><h3>{q.filename}</h3><p>{q.url}</p></div></div><div className="download-status">#{i+1}</div></div><div className="download-item-bottom"><span>Waiting for a download slot</span><button className="download-control cancel-control" onClick={()=>setQueue(x=>x.filter(y=>y.id!==q.id))}>Remove</button></div></article>)}</div>}</section>
 :view==="completed"?<section className="downloads-panel"><div className="section-heading"><div><h2>History</h2><p>Stored locally on this computer.</p></div>{history.length>0&&<button className="download-control" onClick={()=>setHistory([])}>Clear history</button>}</div>{history.length===0?<div className="empty-state"><div className="empty-icon">✓</div><h3>No download history</h3><p>Finished downloads will appear here.</p></div>:<div className="download-list">{history.map(d=>card(d))}</div>}</section>
 :<><section className="add-card"><div className="add-card-copy"><div className="add-icon">↓</div><div><h2>Add a download</h2><p>Paste a URL and Monk3i will identify what it points to.</p></div></div><div className="url-row"><input className="url-input" value={url} onChange={e=>{setUrl(e.currentTarget.value);setResource(null);setError("")}} onKeyDown={e=>{if(e.key==="Enter")inspect()}} placeholder="https://example.com/file.zip"/><button className="secondary-button" onClick={inspect} disabled={inspecting}>{inspecting?"Checking...":"Detect"}</button><button className="primary-button" onClick={add}>+ Add Download</button></div>{resource&&<div className="resource-result"><div><strong>{label(resource.kind)}</strong><span>{resource.filename||"No filename detected"}</span></div><span>{resource.content_type||""}</span><span>{resource.size!==null?formatBytes(resource.size):"Size unknown"}</span></div>}{resource?.kind==="media_page"&&<p className="info-message">Supported media detected. yt-dlp will handle this download.</p>}{error&&<p className="error-message">{error}</p>}</section><section className="downloads-panel"><div className="section-heading"><div><h2>Active Downloads</h2><p>{running} running · {queue.length} queued</p></div><span className="count-badge">{active.length}</span></div>{active.length===0?<div className="empty-state"><div className="empty-icon">↓</div><h3>No active downloads</h3><p>Your active downloads will appear here once you add one.</p></div>:<div className="download-list">{active.map(card)}</div>}</section></>}
 </main>
 {details&&<div className="details-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setDetails(null)}}><section className="details-modal"><div className="details-header"><div><p className="eyebrow">DOWNLOAD DETAILS</p><h2>{details.filename}</h2></div><button className="icon-button" onClick={()=>setDetails(null)}>×</button></div><div className="details-grid"><div><span>Status</span><strong>{details.status}</strong></div><div><span>Downloaded</span><strong>{formatBytes(details.downloaded)}</strong></div><div><span>Total</span><strong>{details.total===null?"Unknown":formatBytes(details.total)}</strong></div><div><span>Speed</span><strong>{formatSpeed(details.speed)}</strong></div><div className="details-wide"><span>URL</span><strong>{details.url}</strong></div><div className="details-wide"><span>Saved path</span><strong>{details.path||"Not available"}</strong></div></div><div className="speed-control"><div><strong>Speed limit</strong><span>{(speedLimits[details.id]??defaultSpeed)===0?"Unlimited":formatSpeed(speedLimits[details.id]??defaultSpeed)}</span></div><select className="speed-select" value={speedLimits[details.id]??defaultSpeed} onChange={e=>setLimit(details,Number(e.currentTarget.value))}><option value={0}>Unlimited</option><option value={131072}>128 KB/s</option><option value={262144}>256 KB/s</option><option value={524288}>512 KB/s</option><option value={1048576}>1 MB/s</option><option value={2097152}>2 MB/s</option><option value={5242880}>5 MB/s</option></select></div></section></div>}
 </div>
}
export default App;
